---
- name: installing httpd and apache
  hosts: all
  become: yes

  tasks: 
   - name: installing httpd
     yum: 
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"

   - name: starting service
     service: 
      name: httpd
      state: started
     when: ansible_os_family == "RedHat"

   - name: installing apache2
     apt: 
      name: apache2
      state: present
     when: ansible_os_family == "Debian"

   - name: starting apache service
     service:
      name: apache2
      state: started
     when: ansible_os_family == "Debian"        

