---
- name: this play book is for installing httpd
  hosts: all
  become: yes

  tasks: 
   - name: installing httpd
     yum:
      name: httpd
      state: installed

   - name: starting service
     service:
      name: httpd
      state: started      
